import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const url=process.env.APP_URL||new URL('../docs/index.html',import.meta.url).href;
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const flush=async()=>page.evaluate(()=>refreshPinyin());
async function audit(label){await flush();const result=await page.evaluate(()=>{const bad=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(n.parentElement?.closest('ruby,script,style,textarea,select,option,input'))continue;if(Object.keys(PINYIN_CHARS).some(c=>n.textContent.includes(c)))bad.push(n.textContent.slice(0,100))}return {bad,nested:document.querySelectorAll('ruby ruby').length,overflow:document.documentElement.scrollWidth>innerWidth}});assert.deepEqual(result.bad,[],label);assert.equal(result.nested,0,label);assert.equal(result.overflow,false,label)}
try{
 await page.goto(url);await audit('home');
 // Simulate an actual pre-pinyin record, then reload: storage key and course ids must stay compatible.
 await page.evaluate(()=>localStorage.setItem(KEY,JSON.stringify({done:[0],answers:{'0-0':1,'0-1':0},wrong:[],notes:{0:'甲乙与日元壬'},last:0,days:['2026-09-10']})));
 await page.reload();assert.equal(await page.evaluate(()=>state.done.includes(0)&&state.notes[0]==='甲乙与日元壬'),true);
 for(const name of ['courses','notes','review','sources']){await page.evaluate(n=>go(n),name);await audit(name)}
 await page.locator('#sourceSearch').fill('壬');await audit('search');assert.ok(await page.locator('#searchResults ruby').count()>0);
 for(let i=0;i<12;i++){await page.evaluate(i=>openLesson(i),i);await audit('lesson '+i);assert.equal(await page.locator('.question').count(),2)}
 await page.evaluate(()=>openLesson(2));await page.locator('#q-2-0 .option').nth(0).click();await audit('wrong feedback');assert.equal(await page.evaluate(()=>state.wrong.includes('2-0')),true);
 await page.evaluate(()=>go('review'));await audit('review question');await page.locator('#q-2-0 .option').nth(1).click();assert.equal(await page.evaluate(()=>state.wrong.includes('2-0')),false);
 await page.evaluate(()=>openLesson(2));await page.locator('#lessonNote').fill('甲甲乙乙，戊己巳已戌戍；<img src=x onerror=alert(1)>');await audit('input preview');assert.equal(await page.locator('#lessonNote + .pinyin-preview ruby[data-hanzi="甲"]').count(),2);assert.equal(await page.locator('#lessonNote + .pinyin-preview img').count(),0);assert.equal(await page.evaluate(()=>state.notes[2].includes('jiǎ')),false);
 for(const type of ['flash','stems','branches','elements','pillars','compass','lines']){await page.evaluate(t=>{practiceType=t;go('practice')},type);await audit(type);if(type==='flash'){await page.locator('.flash').click();await audit('flipped card')}if(type==='stems'){await page.locator('#stem-9').click();await audit('stem detail')}if(type==='branches'){await page.locator('#branch-3').click();await audit('branch detail')}if(type==='pillars'){await page.locator('#p-2-0').click();await audit('day master feedback')}if(type==='compass'){await page.getByRole('button',{name:'旋转 90° ↻'}).click();await page.locator('#compass .n').click();await audit('compass feedback')}}
 await page.evaluate(()=>{page='method';nav();methodStep(0)});await page.locator('#m-stems').fill('甲');await page.locator('.method-work>.row .btn').first().click();assert.equal(await page.locator('#methodNext').isDisabled(),true);
 await page.locator('#m-stems').fill('甲乙丙丁戊己庚辛壬癸');await page.locator('#m-branches').fill('子丑寅卯辰巳午未申酉戌亥');await page.evaluate(()=>checkMethod());await audit('method recall');await page.locator('#methodNext').click();
 for(let i=0;i<4;i++)await page.locator('#m-root'+i).selectOption('根枝花果'[i]);await page.locator('#m-day').selectOption('壬');assert.equal(await page.locator('#m-day').inputValue(),'壬');assert.ok((await page.locator('#m-day option[value="壬"]').textContent()).includes('rén'));await page.evaluate(()=>checkMethod());await page.locator('#methodNext').click();
 for(let i=0;i<8;i++)await page.locator('#m-el'+i).selectOption(['木','水','火','木','水','火','金','水'][i]);await page.evaluate(()=>checkMethod());await page.locator('#methodNext').click();await page.locator('#m-season').selectOption('月份和所处情境不同，所需也不同');await page.evaluate(()=>checkMethod());await page.locator('#methodNext').click();
 for(let i=0;i<3;i++)await page.locator('#m-time'+i).selectOption(['命局','大运','流年'][i]);await page.evaluate(()=>checkMethod());await page.locator('#methodNext').click();for(let i=0;i<6;i++)await page.locator('#m-pair'+i).selectOption('午未申酉戌亥'[i]);await page.evaluate(()=>checkMethod());await page.locator('#methodNext').click();
 await page.locator('#m-wenStart').selectOption('日元为主');await page.locator('#m-wenStem').selectOption('壬');await page.locator('#m-wenTarget').selectOption('寅');await page.evaluate(()=>checkMethod());await audit('wen result');await page.locator('summary').click();await audit('source text');assert.ok(await page.locator('details ruby').count()>22);assert.equal(await page.locator('details img').evaluate(e=>e.complete&&e.naturalWidth>0),true);
 await page.locator('#methodNext').click();await page.locator('#methodSummary').fill('先找日元壬，再清点五行，结合月份与口诀起点。');await page.evaluate(()=>checkMethod());await audit('summary');assert.equal(await page.evaluate(()=>state.method.done.length),8);
 await page.evaluate(()=>go('notes'));const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'导出学习记录 ↓'}).click();const download=await waiting;const saved=await download.path();const exported=JSON.parse(await readFile(saved,'utf8'));assert.equal(exported.state.method.inputs.stems,'甲乙丙丁戊己庚辛壬癸');assert.ok(!JSON.stringify(exported).includes('<ruby'));
 await page.evaluate(()=>localStorage.clear());await page.reload();await page.evaluate(()=>go('notes'));await page.locator('input[type=file]').setInputFiles(saved);await page.waitForFunction(()=>state.method.done.length===8);assert.equal(await page.evaluate(()=>state.notes[0]),'甲乙与日元壬');await audit('restored notes');
 await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});
 for(const width of [390,320]){await page.setViewportSize({width,height:844});for(const p of ['home','courses','notes','sources']){await page.evaluate(p=>go(p),p);await audit(`${width} ${p}`)}for(let i=0;i<8;i++){await page.evaluate(i=>{page='method';nav();methodStep(i)},i);await audit(`${width} method ${i}`)}for(const t of ['stems','branches','pillars','compass','flash']){await page.evaluate(t=>{practiceType=t;go('practice')},t);await audit(`${width} ${t}`)}}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{page='method';nav();methodStep(1)});await flush();await page.screenshot({path:fileURLToPath(new URL('../test-results/mobile.png',import.meta.url)),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{practiceType='stems';go('practice')});await flush();await page.screenshot({path:fileURLToPath(new URL('../test-results/desktop.png',import.meta.url)),fullPage:true});
 assert.deepEqual(errors,[]);console.log(`PASS: ${url} — all pages, all 8 method steps, 12 lessons, all practice modes, every-occurrence audit, polyphones, raw values, prior progress, notes/XSS, export/import, source text, 320/390/1440px layouts; no page errors.`);
}finally{await browser.close()}
