import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {unlockApp} from './access-helpers.mjs';
const url=process.env.APP_URL||new URL('../docs/index.html',import.meta.url).href;
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const clean=selector=>page.locator(selector).first().evaluate(el=>{const n=el.cloneNode(true);n.querySelectorAll('rt').forEach(e=>e.remove());return n.textContent});
async function audit(label){await page.evaluate(()=>refreshPinyin());const result=await page.evaluate(()=>{const bad=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(n.parentElement?.closest('ruby,script,style,textarea,select,option,input'))continue;if(Object.keys(PINYIN_CHARS).some(c=>n.textContent.includes(c)))bad.push(n.textContent.slice(0,60))}return {bad,nested:document.querySelectorAll('ruby ruby').length,overflow:document.documentElement.scrollWidth>innerWidth}});assert.deepEqual(result,{bad:[],nested:0,overflow:false},label)}
try{
 await page.goto(url+'#journey/day');await unlockApp(page);assert.equal(await page.evaluate(()=>journeyUnit),'day');await page.locator('#journeyNext').click();assert.ok(await page.locator('#checkJourney').isDisabled());
 await page.locator('[data-journey-choice="0"]').click();await page.reload();await unlockApp(page);assert.equal(await page.evaluate(()=>journeySession().answers[0].choice),0);assert.equal(await page.evaluate(()=>journeySession().answers[0].first),null);
 await page.locator('#checkJourney').click();assert.equal(await page.locator('#retryJourney').count(),1);await page.evaluate(()=>checkJourney());assert.equal(await page.evaluate(()=>state.academy.reviews['journey:day-1'].attempts),1);await page.locator('#retryJourney').click();await page.locator('[data-journey-choice="1"]').click();await page.locator('#checkJourney').click();assert.equal(await page.evaluate(()=>journeySession().answers[0].first),0);
 const units=JSON.parse(await readFile(new URL('../src/curriculum.json',import.meta.url),'utf8'));
 for(const u of units){await page.evaluate(id=>startJourney(id),u.id);if(await page.evaluate(()=>journeySession().step===0))await page.locator('#journeyNext').click();for(let i=0;i<4;i++){
  if(!await page.evaluate(()=>journeySession().answers[journeySession().step-1]?.checked)){await page.locator(`[data-journey-choice="${u.questions[i].correct}"]`).click();if(i===3)await page.locator('#journeyNote').fill('日元壬，只说明位置。<img src=x onerror=alert(1)>');await page.locator('#checkJourney').click();}
  assert.equal(await page.locator('#journeyNext').count(),1);await page.locator('.journey-source summary').click();assert.ok((await clean('.journey-source blockquote')).includes(u.questions[i].quote));await audit(u.id+' '+i);await page.locator('#journeyNext').click();
 }assert.ok(await page.evaluate(()=>journeySession().completedAt));assert.equal(await page.locator('.journey-review-list li').count(),4);assert.equal(await page.locator('.journey-card img').count(),0);}
 assert.equal(await page.evaluate(()=>Object.values(state.journey.units).filter(u=>u.completedAt).length),10);assert.equal(await page.evaluate(()=>Object.keys(state.academy.reviews).filter(id=>id.startsWith('journey:')).length),40);
 await page.evaluate(()=>go('curriculum'));assert.equal(await page.locator('[data-unit]').count(),10);await page.locator('#curriculumSearch').fill('不存在<img>');assert.equal(await page.locator('[data-unit]').count(),0);await page.locator('#curriculumSearch').fill('方位');assert.equal(await page.locator('[data-unit]').count(),1);await page.locator('#curriculumSearch').fill('');
 await page.evaluate(()=>go('notes'));const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'导出学习记录 ↓'}).click();const download=await downloading,file=await download.path(),backup=JSON.parse(await readFile(file,'utf8'));await page.evaluate(()=>localStorage.clear());await page.reload();await unlockApp(page);await page.locator('input[type=file]').setInputFiles(file);await page.waitForFunction(()=>Object.keys(state.journey.units).length===10);assert.deepEqual(await page.evaluate(()=>state.journey),backup.state.journey);
 await page.locator('input[type=file]').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'zhiyi',version:1,state:{done:[],wrong:[],days:[],notes:{0:'旧笔记'},answers:{}}}))});await page.waitForFunction(()=>state.notes[0]==='旧笔记');assert.equal(await page.evaluate(()=>Object.keys(state.journey.units).length),10);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});for(const route of ['home','curriculum','notes']){await page.evaluate(r=>go(r),route);await audit(width+' '+route)}await page.evaluate(()=>startJourney('day'));await page.evaluate(()=>journeyBack(4));await audit(width+' challenge');}
 await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});await page.setViewportSize({width:1440,height:1050});await page.evaluate(()=>go('curriculum'));await page.locator('.toast').waitFor({state:'detached'});await page.screenshot({path:fileURLToPath(new URL('../test-results/v21-curriculum.png',import.meta.url)),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>startJourney('day'));await page.evaluate(()=>journeyBack(1));await page.screenshot({path:fileURLToPath(new URL('../test-results/v21-journey-mobile.png',import.meta.url)),fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: 40 journey questions, citations, first/corrected attempts, resume, review scheduling, backup/legacy merge, pinyin and responsive layouts.');
}finally{await browser.close()}
