import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {unlockApp} from './access-helpers.mjs';
const url=process.env.APP_URL||new URL('../docs/index.html',import.meta.url).href;
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const go=route=>page.evaluate(r=>go(r),route),clean=selector=>page.locator(selector).first().evaluate(el=>{const n=el.cloneNode(true);n.querySelectorAll('rt').forEach(e=>e.remove());return n.textContent});
async function audit(label){await page.evaluate(()=>refreshPinyin());const result=await page.evaluate(()=>{const bad=[],w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(w.nextNode()){const n=w.currentNode;if(n.parentElement?.closest('ruby,script,style,textarea,select,option,input'))continue;if(Object.keys(PINYIN_CHARS).some(c=>n.textContent.includes(c)))bad.push(n.textContent.slice(0,80))}return {bad,nested:document.querySelectorAll('ruby ruby').length,overflow:document.documentElement.scrollWidth>innerWidth}});assert.deepEqual(result,{bad:[],nested:0,overflow:false},label)}
async function fillStep(i,{wrong=false}={}){await page.locator(`#analysis-${i}-choice`).selectOption(String(wrong?0:[1,0,2,0,0][i]));await page.locator(`#analysis-${i}-source`).selectOption(wrong?'limits':['day','count','seasons','clashes','wenchang'][i]);await page.locator(`#analysis-${i}-boundary`).selectOption(wrong?'2':'0');for(const [key,text] of Object.entries({observation:'日元壬，先辨认实际字与柱位。<img src=x onerror=alert(1)>',reason:'按课程定位栏目，再逐字归类与检查。',uncertain:'数量不能直接定用神，还需月份与实际条件。'}))await page.locator(`#analysis-${i}-${key}`).fill(text)}
try{
 await page.goto(url+'#path');await unlockApp(page);await audit('initial path');
 await page.locator('#diagnosticForm button[type=submit]').click();assert.equal(await page.evaluate(()=>state.studio.diagnostic.completedAt),0);
 await page.getByRole('button',{name:'稍后再做',exact:true}).click();assert.ok(await page.evaluate(()=>state.studio.diagnostic.skippedAt));await page.getByRole('button',{name:'重新诊断',exact:true}).click();
 for(const [i,skill] of ['language','day','count','seasons','clashes','wenchang'].entries())await page.locator(`[data-diagnostic-skill="${skill}"][data-choice="${[1,1,1,2,0,2][i]}"]`).click();
 await page.locator('#diagnosticForm button[type=submit]').click();assert.ok(await page.evaluate(()=>state.studio.diagnostic.completedAt));await audit('diagnostic result');
 await page.reload();await unlockApp(page);assert.equal(await page.locator('.diagnostic-summary article').count(),6);
 const planned=await page.evaluate(()=>dailyPlan().skill);await page.locator('[data-daily-option="1"]').click();assert.ok(await page.evaluate(()=>dailyPlan().conceptDoneAt));assert.equal(await page.evaluate(()=>dailyPlan().skill),planned);assert.ok(await page.evaluate(()=>state.academy.reviews['foundation:'+dailyPlan().skill]));
 for(const id of ['a','b']){
  await go('studio');await page.locator(`[data-studio-case="${id}"]`).click();await page.locator('[data-level="demo"]').click();
  for(let i=0;i<5;i++){await audit(id+' demo '+i);await page.locator('#demoNext').click()}
  assert.ok(await page.evaluate(id=>state.studio.sessions[id+'-demo'].submittedAt,id));
  await page.locator('[data-level="guided"]').click();await page.locator('#showHint').click();await audit('guided hint');
  await page.locator('#checkGuided').click();assert.equal(await page.locator('#guidedNext').isDisabled(),true);
  for(let i=0;i<5;i++){await fillStep(i);assert.equal(await page.locator(`#analysis-${i}-observation + .pinyin-preview img`).count(),0);await page.locator('#checkGuided').click();assert.equal(await page.locator('#guidedNext').isDisabled(),false);await audit(id+' guided '+i);await page.locator('#guidedNext').click()}
  assert.equal(await page.locator('[data-report-step]').count(),5);assert.ok(await page.evaluate(id=>state.studio.sessions[id+'-guided'].hints.includes(0),id));await audit('guided report');
  await page.locator('[data-level="independent"]').click();assert.equal(await page.locator('.report-step,.feedback').count(),0);await page.locator('#submitIndependent').click();assert.equal(await page.locator('#studioReport').count(),0);
  await fillStep(0,{wrong:true});await page.reload();await unlockApp(page);assert.ok((await page.locator('#analysis-0-observation').inputValue()).includes('<img'));assert.equal(await page.locator('.analysis-step img').count(),0);
  await page.locator('#submitIndependent').click();assert.equal(await page.locator('[data-report-step]').count(),5);assert.match(await clean('#studioReport'),/0\s*\/ 5/);assert.match(await clean('.report-step'),/判断待修正/);await audit(id+' missing report');
  await page.locator('[data-report-step="0"] .source-button').last().click();assert.ok((await page.url()).includes('#knowledge/day'));await page.getByRole('button',{name:'← 返回本次分析',exact:true}).click();
  await page.locator('#retryStudio').click();assert.equal(await page.evaluate(id=>state.studio.sessions[id+'-independent'].history.length,id),1);
  for(let i=0;i<5;i++)await fillStep(i);await page.locator('#submitIndependent').click();assert.equal(await page.evaluate(()=>reportSummary(CASES.find(c=>c.id===studioCase),sessionFor()).correct),5);await audit(id+' full report');
 }
 // Reports keep developer credit and plain annotated text, without HTML execution.
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'导出分析报告 ↓',exact:true}).click();const report=await downloading,reportText=await readFile(await report.path(),'utf8');assert.ok(reportText.includes('Daniel Xu'));assert.ok(reportText.includes('壬（rén）'));assert.ok(reportText.includes('语义仍需'));
 await go('knowledge');await page.locator('#knowledgeSearch').fill('待核');assert.equal(await page.locator('.knowledge-node').count(),1);await page.locator('[data-node="limits"]').click();assert.match(await clean('#knowledgeDetail'),/待核口径/);await audit('pending knowledge');
 await page.locator('#knowledgeSearch').fill('不存在的问题<img src=x onerror=alert(1)>');assert.equal(await page.locator('.knowledge-node').count(),0);assert.equal(await page.locator('#knowledgeResults img').count(),0);
 await page.goto(url+'#knowledge/wenchang');await unlockApp(page);assert.match(await clean('#knowledgeDetail h2'),/文昌/);await page.locator('#knowledgeDetail .knowledge-source .source-button').click();assert.equal(await page.locator('#evidenceDialog img').evaluate(el=>el.complete&&el.naturalWidth>0),true);await page.keyboard.press('Escape');
 await go('notes');const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'导出学习记录 ↓'}).click();const backupDownload=await waiting,saved=await backupDownload.path(),backup=JSON.parse(await readFile(saved,'utf8'));assert.equal(backup.developer,'Daniel Xu');assert.equal(backup.productVersion,'2.0.0');assert.equal(Object.keys(backup.state.studio.sessions).length,6);assert.equal(backup.state.studio.sessions['b-independent'].history.length,1);
 await page.evaluate(()=>localStorage.clear());await page.reload();await unlockApp(page);await page.locator('input[type=file]').setInputFiles(saved);await page.waitForFunction(()=>Object.keys(state.studio.sessions).length===6);assert.deepEqual(await page.evaluate(()=>state.studio.sessions),backup.state.studio.sessions);assert.equal(await page.evaluate(()=>state.studio.lastCase),backup.state.studio.lastCase);await page.reload();await unlockApp(page);await page.locator('input[type=file]').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'zhiyi',version:1,state:{done:[],wrong:[],days:[],notes:{0:'旧记录'},answers:{}}}))});await page.waitForFunction(()=>state.notes[0]==='旧记录');assert.equal(await page.evaluate(()=>state.studio.sessions['b-independent'].history.length),1);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});for(const route of ['home','path','studio','knowledge','about','notes']){await go(route);await audit(width+' '+route);assert.ok((await clean('footer')).includes('Daniel Xu'))}await page.evaluate(()=>selectStudio('a','independent'));if(await page.locator('#retryStudio').count())await page.locator('#retryStudio').click();await audit(width+' independent form')}
 await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});await page.setViewportSize({width:1440,height:1050});await go('home');await audit('desktop home');await page.locator('.toast').waitFor({state:'detached'});await page.screenshot({path:fileURLToPath(new URL('../test-results/v2-desktop.png',import.meta.url)),fullPage:true});await page.setViewportSize({width:390,height:844});await go('home');await page.screenshot({path:fileURLToPath(new URL('../test-results/v2-mobile.png',import.meta.url)),fullPage:true});
 assert.deepEqual(errors,[]);console.log(`PASS: ${url} — both cases across all three levels, drafts/reports/retry, missing answers and XSS, diagnostic skip/retest/results, daily plan/review, knowledge search/filter/deep links/evidence, developer credits, report export, full backup and legacy merge, every-occurrence pinyin and 320/390/1440px layouts.`);
}finally{await browser.close()}
