state.academy=safeAcademy(state.academy);
let activeCase=state.academy.lastCase,activeSound='戊',soundAnswered=null,reviewActive=null,reviewAnswered=null,faqQuery='';
function recordReview(id,correct){if(!questionById(id))return;state.academy.reviews[id]=nextReview(state.academy.reviews[id],correct);touch();save()}
function openEvidence(id){const e=EVIDENCE[id];if(!e)return;$('#evidenceDialog')?.remove();const d=document.createElement('dialog');d.id='evidenceDialog';d.className='evidence-dialog';d.innerHTML=`<div class="row between"><span class="badge">${e.kind}</span><button class="btn outline" onclick="document.querySelector('#evidenceDialog').close()">关闭 ×</button></div><h2 style="margin-top:20px">${e.title}</h2><p class="small muted">${e.location}</p><blockquote>${esc(evidenceText(id))}</blockquote>${id==='wenchang'?'<img src="__WEN_IMAGE__" alt="施老师讲义第77页文昌诀" style="width:100%;height:auto">':''}<p class="small muted">当前练习的题目和解析由 App 根据课程整理；此处保留来源类型供核对。</p>`;d.setAttribute('aria-label',e.title);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal()}
function evidenceButton(id){return `<button class="source-button" onclick="openEvidence('${id}')">${EVIDENCE[id].kind} · ${EVIDENCE[id].location} ↗</button>`}
function teachingChart(c){return `<div class="pillars">${c.pillars.map((p,i)=>`<div class="pillar case-pillar"><small>${['年柱','月柱','日柱','时柱'][i]}</small><div>${p[0]}<br>${p[1]}</div></div>`).join('')}</div><p class="small muted centered">教学组合 · 不对应个人出生时间 · 不作独立排盘结果</p>`}
function caseState(c){return state.academy.cases[c.id]??(state.academy.cases[c.id]={step:0,answers:{},note:'',updatedAt:Date.now()})}
function selectCase(id){activeCase=id;state.academy.lastCase=id;save();go('cases')}
function renderCases(){const c=CASES.find(x=>x.id===activeCase)||CASES[0],s=caseState(c),qs=caseQuestions(c);const firstMissing=qs.findIndex((q,i)=>s.answers[i]?.choice!==q.correct);if(s.step>(firstMissing<0?5:firstMissing))s.step=firstMissing;const step=s.step,q=qs[step],a=s.answers[step];$('#view').innerHTML=`<div class="eyebrow">案例教学 · 知易 1.0</div><h1>把一张四柱，读成一条思路。</h1><p class="muted">先作答，再看解析。每一步都能回看课程依据。</p><div class="chips">${CASES.map(x=>`<button class="chip ${x.id===c.id?'active':''}" onclick="selectCase('${x.id}')">${x.title}</button>`).join('')}</div><div class="case-layout"><section class="card case-sheet"><h3>${c.title}</h3><p class="small muted">${c.intro}</p>${teachingChart(c)}<div class="progress"><div style="width:${Math.min(step,5)*20}%"></div></div><p class="small muted">${Math.min(step,5)} / 5 步完成</p><ol class="case-path">${qs.map((x,i)=>`<li class="${i===step?'current':''}">${x.skill}${s.answers[i]?.choice===x.correct?' ✓':''}</li>`).join('')}</ol></section><section class="card case-work">${step<5?`<div class="eyebrow">STEP ${step+1} / 5</div><h2>${q.q}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-case-option="${i}" onclick="answerCase(${i})" ${a?.choice===q.correct?'disabled':''}>${'ABC'[i]}. ${o}</button>`).join('')}</div>${a?`<div class="feedback ${a.choice===q.correct?'':'wrong'}" role="status">${a.choice===q.correct?'判断正确。':'再看一下这个位置。'}${q.why}</div>`:'<p class="small muted">先给出你的判断，提交后再展开分析。</p>'}<div class="section">${evidenceButton(q.source)}</div><button id="caseNext" class="btn" style="margin-top:20px" onclick="caseNext()" ${a?.choice===q.correct?'':'disabled'}>${step===4?'完成并复述 →':'进入下一步 →'}</button>`:`<div class="eyebrow">一张盘，一条分析路径</div><h2>现在，用自己的话连起来。</h2><div class="case-recap">${qs.map((x,i)=>`<article><h3>${i+1}. ${x.skill}</h3><p>${x.why}</p><p class="small muted">作答顺序：${(s.answers[i]?.history||[x.correct]).map(n=>x.options[n]+(n===x.correct?' ✓':' ×')).join(' → ')}</p><span class="small muted">本步作答 ${s.answers[i]?.attempts||0} 次</span> · ${evidenceButton(x.source)}</article>`).join('')}</div><label for="caseNote">我的复述</label><textarea id="caseNote" placeholder="先找日元，再清点五行……" oninput="saveCaseNote(this.value)">${esc(s.note)}</textarea><p id="caseSaved" class="saved">自动保存在本机</p><div class="row"><button class="btn" onclick="selectCase('${c.id==='a'?'b':'a'}')">换一个案例练 →</button><button class="btn outline" onclick="go('compare')">看看月份对照 →</button></div>`}</section></div>`}
function answerCase(choice){const c=CASES.find(x=>x.id===activeCase),s=caseState(c),q=caseQuestions(c)[s.step];if(!q||s.answers[s.step]?.choice===q.correct)return;const prev=s.answers[s.step];if(prev?.choice===choice)return;s.answers[s.step]={choice,history:[...(prev?.history||[]),choice].slice(-50),attempts:(prev?.attempts||0)+1};s.updatedAt=Date.now();recordReview(`case:${c.id}-${s.step}`,choice===q.correct);renderCases()}
function caseNext(){const c=CASES.find(x=>x.id===activeCase),s=caseState(c),q=caseQuestions(c)[s.step];if(q&&s.answers[s.step]?.choice===q.correct){s.step++;s.updatedAt=Date.now();save();renderCases();window.scrollTo(0,0)}}
function saveCaseNote(value){const s=caseState(CASES.find(x=>x.id===activeCase));s.note=value;s.updatedAt=Date.now();$('#caseSaved').textContent=save()?'已保存 ✓':'未保存，请导出备份'}
function renderCompare(){const s=state.academy.compare,q=COMPARE_QUESTION,answered=Number.isInteger(s.choice);$('#view').innerHTML=`<div class="eyebrow">对照实验室 · 同一日元，不同条件</div><h1>同是壬水，月份改变了什么？</h1><p class="muted">沿用老师口述的“农历二月”和“五六月”称呼。这里比较讲解情境，不计算实际节气月。</p><div class="grid practice-grid"><div class="card"><span class="badge">口述情境 A</span><h2>农历二月 · 春寒</h2><p>想象大地刚回春，水尚冷。</p>${evidenceButton('spring')}</div><div class="card"><span class="badge">口述情境 B</span><h2>五六月 · 水少</h2><p>想象天气热，水都快干掉了。</p>${evidenceButton('seasons')}</div></div><section class="card section"><h2>${q.q}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-compare-option="${i}" onclick="answerCompare(${i})" ${s.choice===q.correct?'disabled':''}>${o}</button>`).join('')}</div>${answered?`<div class="feedback ${s.choice===q.correct?'':'wrong'}">${q.why}</div><div class="comparison-table"><table><caption>教学整理 · 条件与讨论一一对应</caption><thead><tr><th>比较点</th><th>二月口述</th><th>五六月口述</th></tr></thead><tbody><tr><th>情境</th><td>春寒，先谈水冷；水多时再谈约束</td><td>水少，需要生助与补充</td></tr><tr><th>老师谈到的所需</th><td>庚金生助、丙火照暖；水多时谈戊土挡、甲木辅助</td><td>庚辛生助、水来补充；该情境下不再要土</td></tr><tr><th>能否固定套用</th><td colspan="2">不能。先保留月份与条件，再理解结论；不是所有壬水共用一套补法。</td></tr></tbody></table></div><p class="small muted">上表依据口述课八（二）、八（五）整理，非逐字原话。完整十二月用神表尚未收录。</p><label for="compareNote">我理解的“条件变化”</label><textarea id="compareNote" oninput="saveCompareNote(this.value)" placeholder="哪些条件变了？哪些不能直接推出？">${esc(s.note||'')}</textarea><p class="saved">自动保存到学习记录</p>`:'<p class="muted small">先选一个判断，再看完整对照。</p>'}</section>`}
function answerCompare(choice){if(state.academy.compare.choice===1||state.academy.compare.choice===choice)return;state.academy.compare={...state.academy.compare,choice,updatedAt:Date.now()};recordReview('compare:seasons',choice===1);renderCompare()}
function saveCompareNote(note){state.academy.compare={...state.academy.compare,note,updatedAt:Date.now()};save()}
function selectSound(c){activeSound=c;soundAnswered=null;speechGeneration++;window.speechSynthesis?.cancel();renderSound()}
function renderSound(){const q=soundQuestion(activeSound);$('#view').innerHTML=`<div class="eyebrow">零基础陪练 · 每个字都读得清楚</div><h1>听一遍，看清字，再选一次。</h1><p class="muted">系统中文语音辅助朗读，非施老师本人声音。拼音始终保留。</p><div class="chips">${SOUND_CHARS.map(c=>`<button class="chip ${c===activeSound?'active':''}" onclick="selectSound('${c}')">${c}</button>`).join('')}</div><div class="grid practice-grid"><section class="card centered"><div class="sound-glyph">${activeSound}</div><div class="row centered" style="justify-content:center"><button class="btn" id="speakChar" onclick="speakCharacter()">▶ 听这个字</button><button class="btn outline" onclick="stopSpeaking()">停止</button></div><p class="small muted" id="speechStatus" role="status">点击朗读；语音由当前浏览器提供。</p><p class="small">戊 · 戌 · 戍<br>己 · 巳 · 已</p></section><section class="card"><h2>${q.q}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-sound-option="${i}" onclick="answerSound(${i})" ${soundAnswered!==null?'disabled':''}>${o}</button>`).join('')}</div>${soundAnswered!==null?`<div class="feedback ${soundAnswered===q.correct?'':'wrong'}" role="status">${q.why}</div>`:''}<button class="btn outline" onclick="selectSound(SOUND_CHARS[(SOUND_CHARS.indexOf(activeSound)+1)%SOUND_CHARS.length])">下一字 →</button><div class="section">${evidenceButton('imagery')}<p class="small muted">字音参考词表中的普通话读音；已、戍是辨形补充，不属于干支。</p></div></section></div>`}
let speechGeneration=0;
function speechStatus(message){if($('#speechStatus'))$('#speechStatus').textContent=message}
function speakCharacter(){const api=window.speechSynthesis;if(!api||!window.SpeechSynthesisUtterance){speechStatus('此浏览器不支持朗读，请按拼音进行文字练习。');return}const voices=api.getVoices().filter(v=>/^zh(-|_)/i.test(v.lang));if(!voices.length){speechStatus('当前未找到中文语音。可稍后再试；拼音和辨字练习仍可使用。');return}api.cancel();const token=++speechGeneration,c=activeSound,u=new SpeechSynthesisUtterance((stems.includes(c)?'天干，':branches.includes(c)?'地支，':'辨形，')+c+'。');u.lang='zh-CN';u.voice=voices.find(v=>/^zh[-_]CN$/i.test(v.lang))||voices[0];u.rate=.75;u.onstart=()=>token===speechGeneration&&speechStatus('正在朗读：'+c);u.onend=()=>token===speechGeneration&&speechStatus('朗读结束，可以再听一遍。');u.onerror=()=>token===speechGeneration&&speechStatus('朗读暂时不可用，请继续看拼音练习。');speechStatus('准备朗读：'+c);api.speak(u)}
function stopSpeaking(){speechGeneration++;window.speechSynthesis?.cancel();speechStatus('已停止朗读。')}
function answerSound(choice){if(soundAnswered!==null)return;soundAnswered=choice;recordReview('sound:'+activeSound,choice===soundQuestion(activeSound).correct);renderSound()}
function reviewEntries(){return Object.entries(state.academy.reviews).filter(([id])=>questionById(id)).sort((a,b)=>a[1].due.localeCompare(b[1].due)||a[1].stage-b[1].stage)}
function renderToday(){const day=dayString(),all=reviewEntries(),due=all.filter(([,x])=>x.due<=day),future=all.filter(([,x])=>x.due>day);const weak={};all.forEach(([id,r])=>{const skill=questionById(id).skill;weak[skill]??={attempts:0,correct:0};weak[skill].attempts+=r.attempts;weak[skill].correct+=r.correct});$('#view').innerHTML=`<div class="eyebrow">今日复习 · 根据真实作答安排</div><h1>今天，补上最不熟的一步。</h1><p class="muted">错题当天重练；答对后按 1、3、7 天安排复习。这是 App 的记忆练习规则。</p><div class="stats"><div class="stat"><strong>${due.length}</strong><small>现在到期</small></div><div class="stat"><strong>${future.length}</strong><small>未来安排</small></div><div class="stat"><strong>${all.reduce((n,[,x])=>n+x.attempts,0)}</strong><small>累计有效作答</small></div></div>${reviewActive?reviewCard():''}<section class="section"><h2>现在到期</h2>${due.length?`<div class="grid practice-grid">${due.map(([id,r])=>`<button class="card" onclick="startReview('${id}')"><h3>${questionById(id).skill}</h3><p class="small">${questionById(id).q}</p><span class="small muted">${r.correct} / ${r.attempts} 次正确 · 开始复习 →</span></button>`).join('')}</div>`:'<div class="card"><p>现在没有到期题目。</p><button class="btn" onclick="go(\'cases\')">从第一个案例开始 →</button></div>'}</section><section class="section"><h2>我的薄弱点</h2><div class="grid practice-grid">${Object.entries(weak).sort((a,b)=>a[1].correct/a[1].attempts-b[1].correct/b[1].attempts).map(([name,v])=>`<div class="card"><h3>${name}</h3><p class="small">正确 ${v.correct} / ${v.attempts} 次</p><div class="progress"><div style="width:${100*v.correct/v.attempts}%"></div></div></div>`).join('')||'<p class="muted">完成一次案例或听读练习后，会生成你的练习记录。</p>'}</div></section><section class="section"><h2>未来安排</h2>${future.length?future.map(([id,r])=>`<p class="future-row"><span>${questionById(id).skill} · ${questionById(id).q}</span><b>${r.due}</b><button class="chip" onclick="startReview('${id}')">提前练习</button></p>`).join(''):'<p class="muted">答对后，这里会显示下一次复习日期。</p>'}</section>`}
function startReview(id){reviewActive=id;reviewAnswered=null;renderToday();$('#reviewCard')?.scrollIntoView({behavior:'smooth',block:'start'})}
function reviewCard(){const q=questionById(reviewActive);if(!q)return '';return `<section id="reviewCard" class="card section"><div class="row between"><h2>复习 · ${q.skill}</h2><button class="chip" onclick="reviewActive=null;renderToday()">收起</button></div><h3>${q.q}</h3><div class="options">${q.options.map((o,i)=>`<button class="option" data-review-option="${i}" onclick="answerReview(${i})" ${reviewAnswered!==null?'disabled':''}>${o}</button>`).join('')}</div>${reviewAnswered!==null?`<div class="feedback ${reviewAnswered===q.correct?'':'wrong'}">${q.why}<br>下次复习：${state.academy.reviews[reviewActive].due}</div>`:''}${evidenceButton(q.source)}</section>`}
function answerReview(choice){if(reviewAnswered!==null)return;reviewAnswered=choice;recordReview(reviewActive,choice===questionById(reviewActive).correct);renderToday()}
function renderAsk(){$('#view').innerHTML=`<div class="eyebrow">课程答疑 · ${FAQ.length} 条有出处的本地问答</div><h1>先问为什么，再回到课程里。</h1><p class="muted">这是按课程整理的问答库，不是实时生成式 AI。未收录的规则保留为待核问题。</p><label for="askQuery">想弄懂哪个概念？</label><input type="search" id="askQuery" placeholder="例如：日元怎么找？文昌查哪里？" value="${esc(faqQuery)}" oninput="faqQuery=this.value;renderFAQResults()"><div id="faqResults" class="section"></div><section class="section"><h2>我的待核问题</h2><div id="pendingQuestions">${state.academy.pending.length?state.academy.pending.map((q,i)=>`<div class="card pending-row"><span>${esc(q)}</span><button class="chip" onclick="removePending(${i})">已解决，移出</button></div>`).join(''):'<p class="muted">课程尚未覆盖的问题可以保存在这里，等补充材料后继续核对。</p>'}</div></section>`;renderFAQResults()}
function renderFAQResults(){const found=findFAQ(faqQuery);$('#faqResults').innerHTML=found.length?found.map(q=>`<article class="card faq-card"><div class="row between"><span class="badge">${q.status||'课程内解释 · 教学整理'}</span><button class="chip" onclick="toggleBookmark('${q.id}')">${state.academy.bookmarks.includes(q.id)?'已收藏 ✓':'收藏'}</button></div><h2>${q.q}</h2><p>${q.answer}</p>${evidenceButton(q.source)}</article>`).join(''):`<div class="card"><h2>现有问答未覆盖这个问题。</h2><p>先留下问题，等待对应课程证据；这里不会用无关口诀补成答案。</p><button class="btn" onclick="savePending()">保存到待核清单</button></div>`}
function toggleBookmark(id){const a=state.academy.bookmarks;state.academy.bookmarks=a.includes(id)?a.filter(x=>x!==id):[...a,id];save();renderFAQResults()}
function savePending(){const q=faqQuery.trim();if(!q)return;if(!state.academy.pending.includes(q))state.academy.pending.push(q);save();renderAsk();toast('已保存待核问题。')}
function removePending(i){state.academy.pending.splice(i,1);save();renderAsk()}
function academyNotesHTML(){return `<div class="card section"><h3>案例复述与收藏</h3>${CASES.map(c=>state.academy.cases[c.id]?.note?`<h3>${c.title}</h3><p style="white-space:pre-wrap">${esc(state.academy.cases[c.id].note)}</p>`:'').join('')}${state.academy.compare.note?`<h3>月份对照复述</h3><p>${esc(state.academy.compare.note)}</p>`:''}<div class="row">${state.academy.bookmarks.map(id=>{const q=FAQ.find(x=>x.id===id);return q?`<button class="chip" onclick="faqQuery='${q.keys[0]}';go('ask')">${q.q} ↗</button>`:''}).join('')}</div><p class="small muted">案例、复述、收藏、待核问题和复习安排均包含在学习记录备份里。</p><button class="source-button" onclick="go('ask')">查看待核问题 ↗</button></div>`}
function updateRoute(){const routes=new Set(['home','method','courses','lesson','practice','review','notes','sources','cases','compare','sound','today','ask']);const hash=location.hash.slice(1);if(routes.has(hash)){page=hash;render();window.scrollTo(0,0)}else if(hash){page='home';render()}}
function routeWrite(p){if(location.hash.slice(1)!==p)history.replaceState(null,'','#'+p)}
function startAcademy(){updateRoute();window.addEventListener('hashchange',updateRoute)}
