// Learning sequence reconstructed from the supplied second oral lesson, not a verbatim numbered method.
const methodTitles=['背熟干支','认四柱、找日元','清点八字五行','看月份、辨所需','分命局、大运、流年','查地支关系','按老师口诀起查','复述思路、再练案例'];
state.method=state.method&&Array.isArray(state.method.done)&&state.method.inputs?state.method:{done:[],inputs:{},step:0};
function methodSet(k,v){state.method.inputs[k]=v;state.method.done=state.method.done.filter(x=>x!==state.method.step);save();let next=$('#methodNext');if(next)next.disabled=true;let f=$('#methodFeedback');if(f)f.innerHTML='<span class="small muted">答案已更新，请重新核对。</span>';let progress=$('#methodProgress');if(progress)progress.textContent='已练会 '+state.method.done.length+' / 8 步'}
function mInput(k,ph=''){return `<input class="method-input" id="m-${k}" value="${esc(state.method.inputs[k]||'')}" placeholder="${ph}" oninput="methodSet('${k}',this.value)">`}
function mSelect(k,opts){return `<select class="method-input" id="m-${k}" onchange="methodSet('${k}',this.value)"><option value="">请选择</option>${opts.map(o=>`<option value="${esc(o)}" ${state.method.inputs[k]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`}
function mField(label,control){return `<label class="method-field"><span>${label}</span>${control}</label>`}
function methodStep(n){state.method.step=n;save();renderMethod();window.scrollTo(0,0)}
function methodProof(quote,where){return `<div class="note"><div class="small muted">施老师课程原话 · ${where}</div>“${quote}”</div>`}
function renderMethod(){let m=state.method,n=Number.isInteger(m.step)&&m.step>=0&&m.step<8?m.step:0;m.step=n;let body='';
if(n===0)body=methodProof('天干必须要记住，那么十个天干、十二个地支必须要记住。','第二节课 · 一')+`<p>先自己默写，核对后再回忆五组物象：大树与花草、太阳与小火、高山与田园、毛坯与精细金属、大海与细雨。</p>${mField('按顺序默写十天干',mInput('stems','从甲开始，标点和空格不影响核对'))}${mField('按顺序默写十二地支',mInput('branches','从子开始'))}<details><summary>记不起来？展开老师的记忆表</summary><p>甲乙木 · 丙丁火 · 戊己土 · 庚辛金 · 壬癸水<br>每组前阳后阴。<br>子丑寅卯辰巳 · 午未申酉戌亥</p></details>`;
if(n===1)body=methodProof('所以我们叫“根、枝、花、果”：年份代表根，月份代表就是一个树的枝子，然后日子代表这个树上的一朵花，然后时辰代表果实的果。','第二节课 · 八（一）')+`<p>本练习固定使用下面的教学组合，只练读图顺序，不对应个人出生时间。</p>${methodChart()}<div class="grid practice-grid">${['年柱','月柱','日柱','时柱'].map((t,i)=>mField(t+'对应',mSelect('root'+i,['根','枝','花','果']))).join('')}</div>${mField('日元是哪一个字？',mSelect('day',stems))}`;
if(n===2)body=methodProof('你分得清楚，它八个字里边多少金、木、水、火、土，有几个金、几个木、几个水，就能点清楚。','第二节课 · 八（四）')+`<p>沿用上一张教学组合。逐字分类后，再核对数量；此处只按八个表面干支的基本五行归类，不展开藏干。</p><div class="grid practice-grid">${['甲','子','丙','寅','壬','午','庚','子'].map((t,i)=>mField(['年干','年支','月干','月支','日干','日支','时干','时支'][i]+' · '+t,mSelect('el'+i,els))).join('')}</div>`;
if(n===3)body=methodProof('它不同的月份，正月、二月、三月、四月、五月，到十二月的壬水，它需要的东西都不一样的。','第二节课 · 八（五）')+`<p>回到老师的壬水课程案例。以下是老师在这两个情境里的传统分析思路，月份沿用他的课程称呼，不在这里换算节气月。</p><div class="grid practice-grid"><div class="card"><h3>课程情境 A · 农历二月</h3><p>老师用春寒、水尚冷的画面解释：谈到庚金来生、丙火照暖；又在“水太多”的条件下谈到戊土挡、甲木辅助。</p></div><div class="card"><h3>课程情境 B · 五六月</h3><p>老师用“水都快干掉了”的画面解释：谈到庚辛来生、水来补充，并说这个情境下不能再要土。</p></div></div>${mField('为什么两次谈到“土”时说法不同？',mSelect('season',['因为只要壬水就必须补土','月份和所处情境不同，所需也不同','五行中数量最少的永远最好']))}<div class="small muted">依据：第二节课 · 八（二）、八（五）。老师提到后续会教十二月份的表；现有资料没有完整表，本练习仅比较这两个课程情境。</div>`;
if(n===4)body=`<div class="note">课程依据：讲稿总结 §六；第二节课 §九（一）。先知道正在读哪张表，再把关系放进去。</div>${mField('出生年、月、日、时组成的基础表',mSelect('time0',['命局','大运','流年']))}${mField('通常约十年一个阶段',mSelect('time1',['命局','大运','流年']))}${mField('某一个具体年份的干支',mSelect('time2',['命局','大运','流年']))}<p class="small muted">本步练概念。起运年龄与顺逆排，仍需按明确的历法口径另行核对。</p>`;
if(n===5)body=methodProof('前面六个跟后面六个正好是冲。','第二节课 · 七')+`<p>先照老师的方法分成两排，再逐组连起来。学会的是“哪两个支相冲”，不是仅凭一个冲字下结论。</p><div class="grid practice-grid">${branches.slice(0,6).map((t,i)=>mField(t+'与谁相冲？',mSelect('pair'+i,branches.slice(6)))).join('')}</div>`;
if(n===6)body=`<div class="note"><div class="small muted">施老师讲义第 77 页 · 文昌诀 · 已对照原页</div>“此诀：以日元为主，年干为辅”</div><p>这次只练文昌诀。先选起查依据，再从老师的表中找目标支，并在练习盘里定位；每一个结果都保留查法。</p>${methodChart()}<div class="grid practice-grid">${mField('起查依据',mSelect('wenStart',['日元为主','年干为辅']))}${mField('起查天干',mSelect('wenStem',stems))}${mField('查得目标地支',mSelect('wenTarget',branches))}</div><details><summary>展开老师的文昌口诀与原页</summary><h3>金口诀：文昌诀</h3><p>孩子书桌、当官办公桌的重要位置！</p><p>甲乙巳午报君知<br>丙戊申宫丁己鸡<br>庚猪辛鼠壬逢虎<br>癸见卯来文昌齐</p><p class="small">原页释文：甲在巳位，乙在午位；丙戊在申位，丁己在鸡位；庚在亥位，辛在鼠位；壬在虎位，癸在卯位。此诀：以日元为主，年干为辅。<br>地支对照：甲→巳、乙→午、丙戊→申、丁己→酉、庚→亥、辛→子、壬→寅、癸→卯。</p><img src="__WEN_IMAGE__" alt="施老师讲义第77页文昌诀原页" style="width:100%;height:auto;border:1px solid var(--line)"></details><p class="small muted">原页将此诀联系到书桌与办公桌位置。本步仅核对口诀目标与柱位，尚未推导住宅方位或布置方案。</p>`;
if(n===7)body=methodProof('先把十个天干、十二个地支，然后它们在排盘里代表什么意思、它们的性格代表什么意思，先去了解。了解了以后，然后我们再来用实际案例来讲。','第二节课 · 九（二）')+`<p>用自己的话复述这次练习。前面的题核对知识点，这一步保留你的学习笔记，不自动判定命理解读正确。</p><label class="method-field"><span>按“日元 → 五行 → 月份 → 所需 → 关系 → 大运流年 → 口诀查法”说一次</span><textarea id="methodSummary" oninput="methodSet('summary',this.value)" placeholder="例如：先找到日柱的壬，知道它是阳水……">${esc(m.inputs.summary||'')}</textarea></label><div class="note">回顾教学组合：日元壬；表面八字中木2、火2、土0、金1、水3。接下来仍要看月份和情境，不能直接把土0解释为一定要补土。文昌以日元壬起查得寅，对应练习盘月支。</div><button class="chip" onclick="methodStep(0)">回到第一步再练一遍 ↻</button>`;
$('#view').innerHTML=`<div class="eyebrow">施老师的教法 · 从基本语言到实战</div><h1>先背得熟，再看得懂。</h1><p class="muted">依据第二节课和讲义整理为 8 步练习；步骤编号是 App 的学习组织，不是老师原话。</p><div class="row between"><span class="small" id="methodProgress">已练会 ${m.done.length} / 8 步</span><span class="badge">跟着老师的顺序做</span></div><div class="chips">${methodTitles.map((t,i)=>`<button class="chip ${i===n?'active':''}" onclick="methodStep(${i})">${i+1}. ${t}${m.done.includes(i)?' ✓':''}</button>`).join('')}</div><div class="card method-work"><h2>${n+1}. ${methodTitles[n]}</h2>${body}<div id="methodFeedback" aria-live="polite" style="margin-top:20px"></div><div class="row between" style="margin-top:22px"><button class="btn" onclick="checkMethod()">${n===7?'保存本次复述':'核对这一步'} ✓</button><button class="btn outline" id="methodNext" onclick="methodStep(${n+1})" ${!m.done.includes(n)||n===7?'disabled':''}>下一步 →</button></div></div><button class="source-button" style="margin-top:20px" onclick="sourceIndex=1;go('sources')">查看施老师第二节课学习摘录 ↗</button>`;
}
function methodChart(){return `<div class="pillars">${['年柱','月柱','日柱','时柱'].map((t,i)=>`<div class="pillar" style="text-align:center"><small>${t}</small><div style="font:32px/1.7 var(--serif)">${['甲','丙','壬','庚'][i]}<br>${['子','寅','午','子'][i]}</div></div>`).join('')}</div><p class="small muted" style="text-align:center">教学组合示意 · 不对应个人出生时间</p>`}
function checkMethod(){let m=state.method,a=m.inputs,n=m.step,ok=false,msg='',clean=s=>(s||'').replace(/[\s，。、,；;|｜]/g,'');
if(n===0){ok=clean(a.stems)===stems.join('')&&clean(a.branches)===branches.join('');msg=ok?'两组顺序都正确。接下来把每个字与物象、阴阳、五行连起来。':'请核对：天干10字、地支12字，按顺序填写。不会的字可展开记忆表后再试。'}
if(n===1){ok=['根','枝','花','果'].every((t,i)=>a['root'+i]===t)&&a.day==='壬';msg=ok?'根枝花果对应正确。日柱壬午，日元是上面的壬。':'年根、月枝、日花、时果；日元是日柱的天干。请再检查。'}
if(n===2){ok=['木','水','火','木','水','火','金','水'].every((t,i)=>a['el'+i]===t);msg=ok?'全部归类正确：木2、火2、土0、金1、水3。数清以后，再看日元出生的月份。':'仍有字未归类正确。甲寅木、丙午火、壬子水、庚金。请逐字再核对。'}
if(n===3){ok=a.season==='月份和所处情境不同，所需也不同';msg=ok?'对。老师的讲法先把月份和自然情境说清，再解释这个情境下的所需。':'请对照两个课程情境：同是壬水，冷暖、水量与条件不同，不能套一个固定补法。'}
if(n===4){ok=['命局','大运','流年'].every((t,i)=>a['time'+i]===t);msg=ok?'三种时间尺度已分清。讨论关系前，先标明正在比较哪一层。':'出生四柱是命局，约十年阶段是大运，具体一年是流年。'}
if(n===5){ok=branches.slice(6).every((t,i)=>a['pair'+i]===t);msg=ok?'六组配对全对：子午、丑未、寅申、卯酉、辰戌、巳亥。':'把子丑寅卯辰巳写在上排，午未申酉戌亥写在下排，再上下对应。'}
if(n===6){let mapping={甲:'巳',乙:'午',丙:'申',戊:'申',丁:'酉',己:'酉',庚:'亥',辛:'子',壬:'寅',癸:'卯'},expected=a.wenStart==='日元为主'?'壬':a.wenStart==='年干为辅'?'甲':null;ok=!!expected&&a.wenStem===expected&&a.wenTarget===mapping[expected];msg=ok?(expected==='壬'?'查法正确：〔日元〕壬 → 寅 → 练习盘月支。命中位置是月柱，不是起查的日柱。':'查法正确：〔年干〕甲 → 巳 → 练习盘四个地支没有巳。保留目标巳，本练习盘没有该命中位置。'):'先看起点：本练习盘日元壬、年干甲。原页规定壬查寅、甲查巳；请对应填写。'}
if(n===7){ok=!!a.summary?.trim();msg=ok?'复述已保存。这是你的学习记录，不代表已自动核定用神或完成命理解读。':'先写下你自己的复述，再保存。'}
if(ok){if(!m.done.includes(n))m.done.push(n);touch();save()}$('#methodFeedback').innerHTML=`<div class="feedback ${ok?'':'wrong'}">${msg}</div>`;$('#methodNext').disabled=!ok||n===7;$('#methodProgress').textContent='已练会 '+m.done.length+' / 8 步';}

