const TUTOR_CONFIG=__TUTOR_CONFIG__;
function safeTutor(raw){return {text:typeof raw?.text==='string'?raw.text.slice(0,1200):'',topic:Object.hasOwn(EVIDENCE,raw?.topic)?raw.topic:'day',questionId:typeof raw?.questionId==='string'&&journeyQuestion(raw.questionId)?raw.questionId:'',updatedAt:Number.isFinite(raw?.updatedAt)?raw.updatedAt:0}}
function mergeTutor(a,b){a=safeTutor(a);b=safeTutor(b);return b.updatedAt>a.updatedAt?b:a}
state.tutor=safeTutor(state.tutor);
let tutorBusy=false,tutorResult=null,tutorError='',tutorController=null,tutorGeneration=0,tutorReturn='';
function cancelTutor(){tutorGeneration++;tutorController?.abort();tutorController=null;tutorBusy=false}
function tutorField(key,value){state.tutor[key]=value;state.tutor.updatedAt=Date.now();tutorResult=null;tutorError='';save();renderTutorResult()}
function openTutorFromJourney(){const u=unitById(journeyUnit),s=journeySession();state.tutor={text:s.note,topic:u.source,questionId:u.questions[3].id,updatedAt:Date.now()};tutorResult=null;tutorError='';tutorReturn='journey';save();go('tutor')}
function openTutorFromStudio(){const s=sessionFor(),parts=Object.entries(s.draft).map(([i,a])=>`${caseQuestions(CASES.find(c=>c.id===studioCase))[i].skill}：${a.observation||''}；${a.reason||''}；还不能判断：${a.uncertain||''}`).join('\n');state.tutor={text:parts.slice(0,1200),topic:'day',questionId:'',updatedAt:Date.now()};tutorResult=null;tutorError='';tutorReturn='studio';save();go('tutor')}
function renderTutor(){const configured=!!TUTOR_CONFIG.endpoint;$('#view').innerHTML=pageHeading('课程助教 · 解释反馈','把你的思路，说清楚一点。','写下自己的理解，让助教对照课程找出需要补充的条件，再给你一个继续思考的问题。')+`<div class="tutor-layout"><section class="card"><div class="row between"><span class="badge">${configured?'AI 服务已配置 · 提交时连接':'AI 服务待连接'}</span>${tutorReturn?`<button class="source-button" onclick="go('${tutorReturn}')">← 返回本次练习</button>`:''}</div>${!configured?'<div class="note"><b>真实 AI 服务尚未连接</b><p>可以先写下理解并查看对应课程依据。连接完成后，这里才会提供生成式反馈。</p></div>':''}<form id="tutorForm" onsubmit="event.preventDefault();submitTutor()"><label class="analysis-label" for="tutorTopic">这次想弄懂的主题</label><select id="tutorTopic" onchange="tutorField('topic',this.value);state.tutor.questionId='';save()" ${tutorBusy?'disabled':''}>${Object.entries(EVIDENCE).map(([id,e])=>`<option value="${id}" ${state.tutor.topic===id?'selected':''}>${e.title}</option>`).join('')}</select>${state.tutor.questionId?`<p class="small muted">练习：${esc(journeyQuestion(state.tutor.questionId).prompt)}</p>`:''}<label class="analysis-label" for="tutorText">我的问题或解释</label><textarea id="tutorText" rows="7" maxlength="1200" placeholder="例如：日柱是壬午，我认为午是日元。我的理解对吗？" oninput="tutorField('text',this.value)" ${tutorBusy?'disabled':''}>${esc(state.tutor.text)}</textarea><p class="small muted">提交时，仅发送框内文字、所选主题与当前题目编号，由服务端选取相关课程片段交给 AI 服务。不会自动上传其他笔记。请使用教学例子，避免填写个人隐私。</p><div class="journey-actions"><button class="btn" type="submit" id="tutorSubmit" ${!configured||tutorBusy?'disabled':''}>${tutorBusy?'正在对照课程…':'提交解释，获取反馈 →'}</button>${tutorBusy?'<button type="button" class="btn outline" onclick="cancelTutor();renderTutor()">停止等待</button>':''}<button type="button" class="btn outline" onclick="openEvidence(state.tutor.topic)">先看课程依据</button></div></form><p class="saved">草稿保存在本机 · 开发者 Daniel Xu</p></section><aside class="card tutor-explainer"><h2>一次只打磨一个判断</h2><ol><li>写出你实际看到了什么。</li><li>说清依据哪条课程内容。</li><li>补上月份、柱位等条件。</li><li>留下现在还不能判断的部分。</li></ol><p class="small muted">助教反馈由 AI 生成，课程引文来自已收录材料。引用匹配不等于推理一定正确，仍请对照课程复核。</p><button class="source-button" onclick="go('ask')">查看现有课程问答 ↗</button></aside></div><div id="tutorResult" aria-live="polite"></div>`;renderTutorResult()}
function validTutorResponse(v){if(!v||!['feedback','pending'].includes(v.status)||typeof v.followUp!=='string'||v.followUp.length>500||!Array.isArray(v.items)||v.items.length>3)return false;return v.items.every(item=>['understood','revise','missing'].includes(item.kind)&&typeof item.text==='string'&&item.text.length<=700&&Array.isArray(item.citations)&&item.citations.length>0&&item.citations.length<=3&&item.citations.every(c=>Object.hasOwn(EVIDENCE,c.id)&&typeof c.quote==='string'&&c.quote.length>=8&&c.quote.length<=500&&evidenceText(c.id).includes(c.quote)))}
function renderTutorResult(){const el=$('#tutorResult');if(!el)return;if(tutorError){el.innerHTML=`<div class="card section" role="alert"><h2>暂时没有取得助教反馈</h2><p>${esc(tutorError)}</p><p class="small muted">你的草稿仍在，可以继续查看课程依据。</p></div>`;return;}if(!tutorResult){el.innerHTML='';return;}const labels={understood:'已经说清',revise:'建议修正',missing:'还需补充'};el.innerHTML=`<section class="card section"><span class="badge">${tutorResult.status==='pending'?'待核 · 暂不作结论':'AI 生成的教学反馈'}</span>${tutorResult.items.map(item=>`<article class="tutor-feedback"><h2>${labels[item.kind]}</h2><p class="preserve-text">${esc(item.text)}</p>${item.citations.map(c=>`<details class="journey-source"><summary>课程原文 · ${esc(EVIDENCE[c.id].location)}</summary><blockquote>${esc(c.quote)}</blockquote>${evidenceButton(c.id)}</details>`).join('')}</article>`).join('')}<div class="note"><b>接下来想一想</b><p>${esc(tutorResult.followUp)}</p></div><p class="small muted">可以修改上面的解释，再提交一次。开发者 Daniel Xu。</p></section>`}
async function submitTutor(){
 if(tutorBusy||!TUTOR_CONFIG.endpoint)return;if(state.tutor.text.trim().length<2){tutorError='请先写下至少两个字的问题或解释。';renderTutorResult();return;}
 let access;try{access=JSON.parse(sessionStorage.getItem('zhiyi-course-unlock-v1')||'null')}catch{}if(!access?.key||!access?.salt){tutorError='此标签页的课程访问状态不可用。请允许会话存储，重新解锁课程后再试。';renderTutorResult();return;}
 tutorBusy=true;tutorError='';tutorResult=null;const generation=++tutorGeneration;tutorController=new AbortController();const controller=tutorController;const timer=setTimeout(()=>controller.abort(),30000),request={text:state.tutor.text,topic:state.tutor.topic,questionId:state.tutor.questionId};renderTutor();
 try{const response=await fetch(TUTOR_CONFIG.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+access.key,'X-Course-Salt':access.salt},body:JSON.stringify(request),signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});if(!response.ok){const messages={400:'请检查问题长度与课程主题。',401:'课程与助教的访问版本不一致，请刷新并重新解锁；如仍出现，请联系开发者。',403:'助教尚未允许这个课程网址访问。离线学习时可继续使用本地答疑。',413:'这次提交过长，请缩短解释。',429:'请求较多，请稍等一分钟再试。',503:'AI 服务尚未就绪或额度暂不可用。',504:'本次等待超时，请稍后重试。'};throw Error(messages[response.status]||'AI 服务暂时不可用，请稍后重试。');}const value=await response.json();if(!validTutorResponse(value))throw Error('这次反馈的课程引用未通过核对，请稍后重试。');if(generation===tutorGeneration)tutorResult=value;
 }catch(error){if(generation===tutorGeneration)tutorError=error.name==='AbortError'?'本次等待已结束。可以稍后重新提交。':error instanceof TypeError?'暂时无法连接助教，请检查网络后重试。':error.message;}
 finally{clearTimeout(timer);if(generation===tutorGeneration){tutorBusy=false;tutorController=null;if(page==='tutor')renderTutor();}}
}
